.PHONY: all
all: notes.pdf slides.pdf

SRC=		preamble.tex XXX.bib
SRC+=		abstract.tex content.tex

notes.pdf: llncs biblatex-lncs
notes.pdf: notes.tex ${SRC}

slides.pdf: slides.tex ${SRC}


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
