.PHONY: all
all: studyguide.pdf

SRC+=		studyguide.tex
SRC+=		${MODULE_FILES}

MODULE_FILES+= 	XXX-abstract.tex XXX.bib

XXX-abstract.tex: ../modules/XXX/abstract.tex
XXX.bib: ../modules/XXX/XXX.bib


${MODULE_FILES}:
	ln -s $^ $@


studyguide.pdf: ${SRC}
studyguide.pdf: llncs biblatex-lncs


.PHONY: distclean
distclean:
	${RM} ${MODULE_FILES}


### INCLUDES ###

INCLUDE_MAKEFILES=<submodule_prefix>/makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
