.PHONY: all
all: studyguide.pdf

LATEXFLAGS+=	-shell-escape

SRC+=		studyguide.tex
SRC+=		${MODULE_FILES}

MODULE_FILES+= 	XXX-abstract.tex XXX.bib

XXX-abstract.tex: ../modules/XXX/abstract.tex
XXX.bib: ../modules/XXX/XXX.bib


${MODULE_FILES}:
	ln -s $^ $@


studyguide.pdf: ${SRC}


.PHONY: clean
clean:
	${RM} studyguide.pdf


.PHONY: distclean
distclean:
	${RM} ${MODULE_FILES}


### INCLUDES ###

INCLUDE_MAKEFILES=<submodule_prefix>/makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
