.PHONY: all
all: notes.pdf

SRC+=		preamble.tex
SRC+=		abstract.tex contents.tex

notes.pdf: llncs biblatex-lncs
notes.pdf: notes.tex
notes.pdf: ${SRC}


INCLUDE_MAKEFILES=<submodule_prefix>/makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
