.PHONY: all
all: notes.pdf slides.pdf

SRC=		preamble.tex
SRC+=		abstract.tex contents.tex

notes.pdf: llncs biblatex-lncs
notes.pdf: notes.tex ${SRC}

slides.pdf: slides.tex ${SRC}


INCLUDE_MAKEFILES=<submodule_prefix>/makefiles
include ${INCLUDE_MAKEFILES}/tex.mk
